FROM java:8
EXPOSE 8761
ADD C:\Program Files (x86)\Jenkins\workspace\room-eureka-server\room-eureka-server\target\room-eureka-server.jar room-eureka-server.jar
ENTRYPOINT ["java","-jar","room-eureka-server.jar"]